DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS mpa
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Directors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    description  VARCHAR(255) NOT NULL,
    release_date DATE         NOT NULL,
    duration     INTEGER      NOT NULL,
    mpa_id       BIGINT,
    CONSTRAINT films_mpa_fk FOREIGN KEY (mpa_id) REFERENCES Mpa (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    login    VARCHAR(100) NOT NULL,
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(255) NOT NULL,
    is_positive BOOLEAN      NOT NULL,
    user_Id     BIGINT       NOT NULL,
    film_Id     BIGINT       NOT NULL,
    useful      BIGINT,
    CONSTRAINT reviews_user_fk FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT reviews_film_fk FOREIGN KEY (film_id) REFERENCES films (id)
);
CREATE TABLE IF NOT EXISTS FILM_DIRECTORS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id     BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    CONSTRAINT FILM_DIRECTORS_FILMS_FILM_ID_fk FOREIGN KEY (film_id) REFERENCES FILMS (id) ON DELETE CASCADE,
    CONSTRAINT FILM_DIRECTORS_DIRECTORS_DIRECTOR_ID_fk FOREIGN KEY (director_id) REFERENCES Directors (id) ON DELETE CASCADE,
    CONSTRAINT unique_film_director UNIQUE (film_id, director_id)
);

CREATE TABLE IF NOT EXISTS reviews_grades
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_Id     BIGINT  NOT NULL,
    reviews_id  BIGINT  NOT NULL,
    is_positive boolean NOT NULL,
    CONSTRAINT unique_user_review_is_positive UNIQUE (user_Id, reviews_id, is_positive),
    CONSTRAINT grade_user_fk FOREIGN KEY (user_Id) REFERENCES users (id),
    CONSTRAINT grade_review_fk FOREIGN KEY (reviews_Id) REFERENCES reviews (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT FILM_GENRES_FILMS_FILM_ID_fk FOREIGN KEY (film_id) REFERENCES FILMS (id) ON DELETE CASCADE,
    CONSTRAINT FILM_GENRES_GENRES_GENRE_ID_fk FOREIGN KEY (genre_id) REFERENCES GENRES (id),
    CONSTRAINT unique_film_genre UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS Friendship

(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    CONSTRAINT Friends_unique UNIQUE (user_id, friend_id),
    CONSTRAINT Friends_USERS_USER_ID_fk FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    CONSTRAINT Friends_USERS_USER_ID_fk_2 FOREIGN KEY (friend_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Film_likes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT Film_likes_unique UNIQUE (film_id, user_id),
    CONSTRAINT Film_likes_FILMS_FILM_ID_fk FOREIGN KEY (film_id) REFERENCES FILMS (id) ON DELETE CASCADE,
    CONSTRAINT Film_likes_USERS_USER_ID_fk FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

comment on column Directors.id is 'ID режиссера';
comment on column Directors.name is 'Имя режиссера';